### ISSUE TITLE
Can't drag more than 5 items inside Outlook

### ISSUE THREAD

**Issue by hoolius** [tonyfederer/OutlookFileDrag#26]
With v1.0.8 installed, we can't drag more than five items to another folder within Outlook. If I select five items, I can drop them to another folder (or PST). If I select six, the drag/drop no longer works.

`2019-02-11 10:33:23,004 [VSTA_Main] INFO  OutlookFileDrag.DragDropHook [(null)] - Drag started
2019-02-11 10:33:23,005 [VSTA_Main] INFO  OutlookFileDrag.DragDropHook [(null)] - Virtual files found -- starting new drag adding CF_HDROP format
2019-02-11 10:33:23,012 [VSTA_Main] WARN  OutlookFileDrag.DragDropHook [(null)] - Dragging error
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at OutlookFileDrag.DataObjectHelper.ReadHGlobalIntoStream(IntPtr handle, Stream stream) in C:\Users\Tony\Source\Repos\OutlookFileDrag\OutlookFileDrag\DataObjectHelper.cs:line 396
   at OutlookFileDrag.DataObjectHelper.ReadMediumIntoStream(STGMEDIUM medium, Stream stream) in C:\Users\Tony\Source\Repos\OutlookFileDrag\OutlookFileDrag\DataObjectHelper.cs:line 284
   at OutlookFileDrag.DataObjectHelper.GetFilenamesUnicode(IDataObject data) in C:\Users\Tony\Source\Repos\OutlookFileDrag\OutlookFileDrag\DataObjectHelper.cs:line 194
   at OutlookFileDrag.DataObjectHelper.GetFilenames(IDataObject data) in C:\Users\Tony\Source\Repos\OutlookFileDrag\OutlookFileDrag\DataObjectHelper.cs:line 69
   at OutlookFileDrag.DragDropHook.DoDragDropHook(IDataObject pDataObj, IntPtr pDropSource, UInt32 dwOKEffects, UInt32& pdwEffect) in C:\Users\Tony\Source\Repos\OutlookFileDrag\OutlookFileDrag\DragDropHook.cs:line 90`

**Comment by tonyfederer** [comment]
This bug has been fixed in version 1.0.10.

https://github.com/tonyfederer/OutlookFileDrag/releases/tag/v1.0.10

**Comment by tonyfederer** [comment]
Hoolius, can you please try version 1.0.10 and confirm this resolves your issue?

**Comment by hoolius** [comment]
Sorry Tony! I forgot to come back and let you know. The new version took care of it. Appreciate it.
